### ISSUE TITLE
Aprstastic not working

### ISSUE THREAD

**Issue by tristanmoney** [afourney/aprstastic#37]
Aprstastic isn't working for me currently. I'm not sure if it is related, but APRS.fi went down last night due to a UPS issue and is only partially operational now. Maybe this also impacted aprs-IS?

I restarted aprstastic and it seems to connect properly and send data, but there is no reply from messages to APNGIX.

**Comment by afourney** [comment]
@tristanmoney Hi, I lost power and internet for 3 days so I missed your messages, but I see them making it to APRS.fi. 

I'm not sure where APRS.fi is hosted, but we had major power outages here from that cyclone that went by.

Let me know if you are still having issues, and we can work through them.
